name: CI

on:
  push:
    branches: '**'
    tags-ignore: '**'
    paths:
      - 'src/**'
  pull_request:
    branches: '**'
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with: { fetch-depth: 0 }

        - name: Install Dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y g++-10-multilib

        - name: Build
          run: make -j$(nproc)

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: msf-linux
            path: materialsystemfix.so
            if-no-files-found: error

  build-win:
    name: Windows Build
    runs-on: windows-2019
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with: { fetch-depth: 0 }

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v2

        - name: Build
          run: msbuild -m -t:materialsystemfix -p:"Platform=x86" MSF.sln

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: msf-windows
            path: |
              bin\materialsystemfix.dll
              bin\materialsystemfix.pdb
            if-no-files-found: error
